version: "3.8"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  fastapi_app:
    build: .
    command: python3 main.py
    depends_on:
      - redis
    volumes:
      - .:/app/
    working_dir: /app/ocr_analysis
    ports:
      - "8000:8000"
